name: Lint
on: [push, pull_request]
jobs:
    lint:
        name: ktlint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2.3.4

            - name: Install java
              uses: actions/setup-java@v1.4.3
              with:
                  java-version: '13.0.2' # The JDK version to make available on the path.
                  java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
                  architecture: x64 # (x64 or x86) - defaults to x64

            - name: Install dependencies
              run: ./gradlew dependencies

            - name: run linter
              run: ./gradlew lintKotlin
