name: Lint
on: [push, pull_request]
jobs:
    lint:
        name: ktlint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2.1.0

            - name: Install java
              uses: actions/setup-java@v1.3.0
              with:
                  java-version: '11.0.6' # The JDK version to make available on the path.
                  java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
                  architecture: x64 # (x64 or x86) - defaults to x64

            - name: Install dependencies
              run: ./gradlew dependencies

            - name: run linter
              run: ./gradlew lintKotlin
